### ISSUE TITLE
Intro quest

### ISSUE THREAD

**Issue by cashenkes** [Goldiriath/Quests#1]
To do:
 - [x] script quest
    - [x] main quest file
    - [x] innkeeper dialogue
    - [x] stable master dialogue
    - [x] blacksmith dialogue
 - [x] test quest

- The player spawns in the inn in Vyrandell in a little room.

~Player joins the server (for the first time)~

''You wake up, but you do not remember how you got here. Maybe you should have a look around.''
- The player then gets to walk around a bit till he goes downstairs.

Innkeeper: '' Hey you, you're finnaly awake, come here and talk for a seccond.''

The player walks to the Innkeeper and right clicks on him.

Innkeeper: ''Glad your finnaly awake, a fisherman from the town to the southeast of us brought you in a couple of days ago. After you have repaid me for the room you used, you should go and see him.''
(player option) 1) Why pay you? - 2) But I dont have anything to pay with. 

1) Innkeeper: ''You didn't think I would let you stay for free did you? 
(player option) 1) this is ridiculous, and even if i wanted to pay I would have nothing to pay with. - 2) But I dont have anything to pay with. 
1,1) Innkeeper: you wouldn't need that much to pay me anyway, since I stuffed you in the cheapest room I have. And now go fetch me some hay, I'm not going to let you leave without payment.
1,2) Innkeeper: Thats alright the room wasn't that expensive anyway. If you fetch me some hay, you're free to go.

2) Innkeeper: Thats alright the room wasn't that expensive anyway. If you fetch me some hay, you're free to go.

Innkeeper: ''You can get some hay from the stable, it shouldn't be that hard to find. And now go I have other matters to attend too. (repeats if spoken to again, untill the player has a hay block in his/her inventory)
- The player now walks to the stable and right clicks the Stabblemaster

Stabblemaster: Hello there, what can I do for you?
(player option) 1) I need some hay to pay the Innkeeper for the room I used. - 2) The Innkeeper send me to collect some hay.
1) I dont have a lot of hay, but I can give you some.
(player option) 1) Thank you very much. - 2) I'll go bring the hay to the Innkeeper then.

-player x recieves 1 hay block, and brings the hayblock back to the Innkeeper.

**EDIT**: Yaml files now available on the repo:
- _quest_intro.yml_
- _dialog_stablemaster.yml_
- _dialog_innkeeper.yml_

**Comment by JeromSar** [comment]
Well, what do you guys think? @Goldiriath/questing

**Comment by derpfacedirk** [comment]
I may be biased (seeing as I co-wrote it) but I think it looks good

**Comment by JeromSar** [comment]
Might want to add the files to this repo. :) @derpfacedirk

**Comment by cashenkes** [comment]
Blacksmith script:
- The player has just given the hay from the stablemaster to the innkeeper. The innkeeper has now send the player to optain their first piece of gear from the blacksmith.

Blacksmith: Hello there, what can i do for you?
(player option) 1) The innkeeper send me. 2) Im here to see if I can get my first gear.
1,1) And I think thaty means that you are looking for some gear?
(player option) 1) What else? 2) Yes sir.
1,1,1) (Innkeeper_dislike = 1) I can see why the Innkeeper doesn't like you, but I have some gear left over for people such as yourself...
1,1,1) (Innkeeper_dislike = 0) Hmmm, I would appreciate it if you could be a little less sarcastic, but I have some gear left over for people such as yourself...
         I found a crappy bow and a rusty sword, you can chose which piece of trash you want.

1,2 (edit by @derpfacedirk) + 1.1.2) I think that i have some gear that you can take. I found a bow and an old sword, you can chose which of those you want.

(player option) 1) I'll chose the bow. 2) I think the sword fits me.

**Comment by Hakhaktak** [comment]
Okay, what if we can do instead of 

''You wake up, but you do not remember how you got here. Maybe you should have a look around.''

that the character talks to itself. In thoughts. Also, separating thoughts of spoken words by grey colour instead of white.

"Where am I?"
"What happened"
"Looks like I fell asleep or something, but I can't remember anything."
"And who took care of me?!"

_Intro Innkeeper_

''Hey you, you're finally awake. It was about getting time, huh? Come to the living room and let's talk for a second.''

(I added a bit more text to give it a bit more atmosphere)
- Player
  "Hmm, I should come over I guess, it doesn't look like I have a choice, and after all, he took care of me"
- Inkeeper
  'Glad your finally back on earth, a fisherman from the town to the southeast of us brought you in a couple of days ago. After you have repaid me for the room you used, you should go and see him.''
- Player
  "Yeah.. That was predictable"
  (player option) 
  1) This is ridiculous, and even if I wanted to pay I would have nothing to pay with.
  2) I'm sorry, but I don't have anything to pay you with.

1,1) Innkeeper: you wouldn't need that much to pay me anyway, since I stuffed you in the cheapest room I have. And now go fetch me some hay, I'm not going to let you leave without payment.
1,2) Innkeeper: Thats alright the room wasn't that expensive anyway. If you fetch me some hay, you're free to go.

Do you guys understand what I mean with the thoughts? I'm currently using it as well in a quest Siert and I are working on. Again, I changed some lines to make give it a bit more atmosphere.

**Comment by Hakhaktak** [comment]
Oh and, for all of us, I think it'd be a good idea to use a spell corrector. It takes out most of the errors. For grammar, we may need a native speaker (ahum KYLE) to check that. Also, British spelling or American? Color or Colour? I favour the British spelling, but I have to admit that I'm not always consequent, also because I sometimes don't know which spelling it is. 

For good translations: http://www.interglot.nl/woordenboek/nl/en/zoek?q=toegeven&m=

Use a synonyms to make your lines more interesting. It'll make it look less repetitive and make it look more pleasing to the eye.

**Comment by Hakhaktak** [comment]
Inkeeper is a good example of a stupid error I could've prevented whilst using a spellchecker ;-;

**Comment by derpfacedirk** [comment]
First of all, I think we shouldn't keep the dialogs as short as possible, in my experience people will want to skip most of this and seeing as were basically forcing them to listen to it the least we can do is keep it as short as possible
I would prefer british spelling, but in general I don't think it is really necessary to be incredibly consistent with this

**Comment by cashenkes** [comment]
I do not think that choosing British or American spelling is really important atm, we just have to be consistent in one dialog. Also Hylke its great that you are making a quest, and it would also be great if you can make an issue about that quest, so we can see what it is about.

**Comment by derpfacedirk** [comment]
Implemented in 37185d49a6bff0d5e4eb20b1548e780e24c91304
